source 'https://rubygems.org'

gem 'httparty'
gem 'rspec'
gem 'cucumber', '>=2.4.0'
#gem 'require_all'
#gem 'parallel_split_test'
gem 'rake'
#gem 'json', '~> 1.0'
gem 'parallel_cucumber'
#gem 'syntax'
gem 'report_builder'
