# config/cucumber.yaml
<% report_out_dir = "#{ENV['OUT_DIR']}" %>
<% test_batch_id = "#{ENV['TEST_PROCESS_NUMBER']}" %>

parallel_reports: >
  --format json --out <%=report_out_dir%>/test<%=test_batch_id%>.json

